# -*- coding: utf-8 -*-
"""Data Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4yN5S3z8x8aeCPCswXZgg6XxTRl7fUT
"""

#Import libraries
import os
import random
import shutil
import tensorflow as tf
import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator

!gdown https://storage.googleapis.com/wandb_datasets/nature_12K.zip  # Data Download
!unzip "/content/nature_12K.zip"                                     # Unzip the folder
!find . -name "*.DS_Store" -type f -delete                           # Delete DS_store file name

# list of class names
temp = os.listdir("inaturalist_12K/train")
class_names = [name for name in temp if name != ".DS_Store"]
print("The names of the classes are:")
print(class_names)

num_classes = len(class_names)
print(f"Number of classes = {num_classes}\n")

T = 0
T_test = 0

for each_class in class_names:
    train_images = os.listdir("inaturalist_12K/train/"+each_class)
    test_images = os.listdir("inaturalist_12K/val/"+each_class)
    filtered_images = list(filter(lambda x: x!=".DS_Store", train_images))
    filtered_test_images = list(filter(lambda x: x!=".DS_Store", test_images))
    T = T + len(filtered_images)
    T_test = T_test + len(filtered_test_images)

print(f"Total number of training images = {T}")
print(f"Total number of test images = {T_test}\n")

#Creating validation set
# Fraction of images to use in the validationset
val_split_fraction = 0.1

# Create a new directory for the validation set
os.mkdir("inaturalist_12K/validation/")

for each_class in class_names:
    os.mkdir("inaturalist_12K/validation/"+each_class)
    train_images = os.listdir("inaturalist_12K/train/"+each_class)
    filtered_images = list(filter(lambda x: x!=".DS_Store", train_images))
    count = len(filtered_images)
    random.shuffle(filtered_images) # Shuffle the training images

    validation_images = filtered_images[:round(val_split_fraction*count)]

    for im in validation_images:
        shutil.move("inaturalist_12K/train/"+each_class+"/"+im, "inaturalist_12K/validation/"+each_class+"/"+im)
